### ISSUE TITLE
Access to wrong workspace data

### ISSUE THREAD

**Issue by AdeTheux** [renatomoor/slack-alfred-workflow#1]
So I've followed the steps to install and configure your Slack Alfred workflow, the app/bot has been configured correctly, I've got all the required dependencies etc.
After running ```update slack-workflow``` as the doc states, I can see data displayed in Alfred's box… but the list of channels or users displayed is not coming from my workspace.

<img width="356" alt="image" src="https://user-images.githubusercontent.com/1615367/228273362-14c8b465-d04b-49dc-a618-54dedf8efddd.png">

I see your name, your channels etc. Not trying to post anything, but this seems like a big security risk for you, or am I missing something obvious?
Thanks

**Comment by renatomoor** [comment]
Hello @AdeTheux,

I made a mistake while exporting the workflow installer,
I exported it with some unnecessary data, including the node_modules and some cache files,
So, no security risk for the moment, and thank you for noticing.

Can you please try to install it again?
I've replaced the worflow installer: [slack-workflow](https://github.com/renatomoor/slack-alfred-workflow/raw/main/docs/documents/slack-workflow.alfredworkflow)

Thanks for your help.

**Comment by AdeTheux** [comment]
Thanks for the updated workflow.
I've deleted the previous one, installed the new one, configured it with token and secret, ran ```update slack-workflow``` but now I don't have any data available anymore, including coming from my own workspace 🤔 
<img width="369" alt="image" src="https://user-images.githubusercontent.com/1615367/228286096-15f4afe0-f0e5-47e2-92d0-d59a417a9e29.png">

**Comment by renatomoor** [comment]
@AdeTheux 

I've just tested it on other computers,
It is working fine. 
So, what I recommend is to check:

 1. Homebrew is installed on your pc
 2. You have given the correct scopes to the Slack app and reinstalled the app after giving the correct scopes
 3. You need to run the command `install slack-workflow` before running the update. (This command can take sometime). 
     You can check if it worked correctly by clicking right in the workspace and clicking open in finder.
     
<img width="514" alt="image" src="https://user-images.githubusercontent.com/24254515/228299854-95c30ee1-999b-4ae3-9ab3-3a46281c7503.png">

Then you should see this folder: node_modules
<img width="306" alt="image" src="https://user-images.githubusercontent.com/24254515/228300209-8a9378eb-d54b-406c-9b73-893e17a6db06.png">

If that's the case now you can run the script `update slack-worlflow`

Also check that you have entered the correct values in the workflow configuration.

I hope this helps you.
If not, please let me know.

**Comment by AdeTheux** [comment]
Wonderful, thanks again for the help!
I've started from scratch again, and realised the user error issue 🤦🏻‍♂️

1. I added the scopes to the ```Bot Token Scopes``` section, not the user one
2. I didn't publish the changes after modifying the Slack app.

After those changes, I updated everything and it now works flawlessly.
Thanks again!

**Comment by AdeTheux** [comment]
One last question: any way to access private channels, like it's possible for public ones? Thanks

**Comment by renatomoor** [comment]
@AdeTheux 
I've added the private channels and a new command to upgrade the slack-worflow,

So for this time you have to install it again manually by following the installation from [these steps](https://renatomoor.github.io/slack-alfred-workflow/getting-started.html#_3-installing-the-workflow).

I hope it works.

**Comment by AdeTheux** [comment]
Thanks, that's very cool! I'll try tomorrow, this time I shouldn't fail 🙂

**Comment by AdeTheux** [comment]
Well, someone failed miserably. Or the workflow has an issue with the channels.js update process?

I deleted the old workflow, installed the new one, ran the install and update script. The update script seems to work fine for users (and I @user in the Alfred box), but channels haven't been updated properly.
I can't find any channels via Alfred, public or private.

Update process ended with "channels updated", but before that there was this:
![image](https://user-images.githubusercontent.com/1615367/229077002-ddb7165d-9d93-4c80-9e47-0f1b57e95f96.png)

**Comment by AdeTheux** [comment]
All works fine now, thanks again!
