### ISSUE TITLE
search:read token missing

### ISSUE THREAD

**Issue by michaelfallik** [renatomoor/slack-alfred-workflow#2]
Hey there! Following the steps to install this workflow and ran into an issue:

In the instructions under _2. Tokens and installing app_ the Bot Token Scopes named "search:read" doesn't appear in the list and can't be added. 
![CleanShot 2023-04-04 at 11 46 44](https://user-images.githubusercontent.com/68760057/229738868-784cd232-3967-4a64-b7cf-cc472c822f1c.png)

**Comment by renatomoor** [comment]
Hello @michaelfallik 

The problem is that you are adding the scopes in the **Bot Token Scopes** section and that is wrong,
You need to add the scope in the **User Token Scopes** section.

**Comment by michaelfallik** [comment]
Thanks @renatomoor, that works!

**Comment by michaelfallik** [comment]
Thanks @renatomoor, that works!
